RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-00 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-01 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-02 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-03 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-04 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-05 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-06 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-07 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-08 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-09 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-10 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-11 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-12 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-13 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-14 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-15 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-16 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-17 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-18 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-19 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-20 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-21 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-22 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-23 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-24 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-25 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-26 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-27 -e NONE -i 16 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-28 -e NONE -i 16 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-29 -e NONE -i 16 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-30 -e NONE -i 16 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-31 -e NONE -i 16 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-32 -e NONE -i 16 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-33 -e NONE -i 16 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-34 -e NONE -i 16 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-35 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-36 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-37 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-38 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-39 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-40 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-41 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-42 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-43 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-44 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-45 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-46 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-47 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-48 -e NONE -i 113 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-49 -e NONE -i 113 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-50 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-51 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-52 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-53 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-54 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-55 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-56 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-57 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-58 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-59 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-60 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x4/shadow/Tree-shadow-61 -e NONE -i 1 -k -a 64 -c


RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-00-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-01-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-02-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-03-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-04-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-05-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-06-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-07-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-08-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-09-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-10-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-11-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-12-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-13-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-14-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-15-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-16-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-17-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-18-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-19-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-20-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-21-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-22-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-23-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-24-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-25-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-26-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-27-x1 -e NONE -i 16 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-28-x1 -e NONE -i 16 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-29-x1 -e NONE -i 16 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-30-x1 -e NONE -i 16 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-31-x1 -e NONE -i 16 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-32-x1 -e NONE -i 16 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-33-x1 -e NONE -i 16 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-34-x1 -e NONE -i 16 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-35-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-36-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-37-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-38-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-39-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-40-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-41-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-42-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-43-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-44-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-45-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-46-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-47-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-48-x1 -e NONE -i 113 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-49-x1 -e NONE -i 113 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-50-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-51-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-52-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-53-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-54-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-55-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-56-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-57-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-58-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-59-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-60-x1 -e NONE -i 1 -k -a 64 -c
RGBA-EATER.py -n trees/x1/shadow/Tree-shadow-61-x1 -e NONE -i 1 -k -a 64 -c